/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openailab_speechrecognition_SpeechRecognitionJNI */

#ifndef _Included_com_openailab_speechrecognition_SpeechRecognitionJNI
#define _Included_com_openailab_speechrecognition_SpeechRecognitionJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openailab_speechrecognition_SpeechRecognitionJNI
 * Method:    ASRInit
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_openailab_speechrecognition_SpeechRecognitionJNI_ASRInit
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jdouble);

/*
 * Class:     com_openailab_speechrecognition_SpeechRecognitionJNI
 * Method:    ASRStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openailab_speechrecognition_SpeechRecognitionJNI_ASRStart
  (JNIEnv *, jclass);

/*
 * Class:     com_openailab_speechrecognition_SpeechRecognitionJNI
 * Method:    ASRStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_openailab_speechrecognition_SpeechRecognitionJNI_ASRStop
  (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
